/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <Ctl/led_ctrl.h>   // LED业务逻辑接口
#include "Ifx_Types.h"  //定义 TriCore 架构的通用数据类型（如uint8_t/uint32_t、boolean）
#include "Ifx_Cfg.h"    //工程的全局配置头文件，包含 SSW、外设等模块的配置宏
#include "IfxCpu.h"     //TriCore CPU 核心的寄存器 / 函数定义（如中断使能、核 ID 获取），是操作 CPU 核心功能的基础头文件。
#include "IfxWtu.h"     //Watchdog Timer Unit（看门狗单元）的函数定义，包含看门狗的使能、禁用、喂狗等函数
#include "IfxPort.h"
#include "port_cfg.h"   // Port配置接口
#include "dio.h"
#include "led_ctrl.h"
#include "led_cfg.h"


void core0_main(void)   //Core0 的主函数入口,由 SSW 启动代码最终调用
{
    IfxCpu_enableInterrupts();  //使能 Core0 的全局中断
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());  //禁用 Core0 的 CPU 看门狗和系统安全看门狗。
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    

/**********************************************************************************************************************
* User Practice
* START
*********************************************************************************************************************/

    /**
     * Core0主函数入口
     * 仅负责初始化与主循环任务调度，无底层硬件与具体应用逻辑的依赖（符合AUTOSAR分层规范）
     * 核心职责是 “系统级集成与调度”（确保模块初始化顺序、任务调度正常），而非 “业务细节的实现”（如 LED 初始状态、闪烁逻辑）
     */

    // 1. Port驱动初始化（必须优先执行，符合AUTOSAR Port驱动初始化时序）
    Port_Cfg_Init();
    
    // 2. LED模块初始化（集成工程师仅需调用接口，同时确认关键配置型号，无需关心内部逻辑）
    //Led_Ctrl_Init();
    Led_Ctrl_Init(&FashionableCarConfig);
    //Led_Ctrl_Init(&BasicCarConfig);

    // 3. 主循环：调度LED业务逻辑（集成工程师仅需调用接口，无需关心内部逻辑）
    while(1)
    {
        Led_Ctrl_Handle(); // 调用业务逻辑模块
    }

//前 Port_Cfg_Init 和 Led_Ctrl_Init 的先后顺序依赖于 main.c 里的手动排序。
//后续可引入一个 EcuM (ECU State Manager) 模块，统一管理各层级的初始化序列（Power-up -> MCU Init -> Port Init -> Driver Init -> App Init）。



/**********************************************************************************************************************
* User Practice
* END
*********************************************************************************************************************/

}