/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "IfxCpu.h"     //TriCore CPU 核心的寄存器 / 函数定义（如中断使能、核 ID 获取），是操作 CPU 核心功能的基础头文件。
#include "IfxWtu.h"     //Watchdog Timer Unit（看门狗单元）的函数定义，包含看门狗的使能、禁用、喂狗等函数

#include "port_cfg.h"   // Port配置接口
#include "led_ctrl.h"
#include "led_cfg.h"
#include "multicore_resm.h"


//IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0; // 全局变量定义，被编译器放入全局数据段 (Data/Bss Section)，IFX_ALIGN(4) 是一种编译器指令
/* 使用 GCC 的属性语法，强制将变量放入非缓存的共享段 */
/* 这是最标准的写法，它会自动展开为 GCC 识别的属性 */
//IfxCpu_syncEvent g_cpuSyncEvent __attribute__ ((section (".bss_cpu0.migration_unlimited"))) = 0;
IfxCpu_syncEvent g_cpuSyncEvent __attribute__ ((section (".lmudata"))) = 0;

void core0_main(void)   //Core0 的主函数入口,由 SSW 启动代码最终调用
{
    IfxCpu_enableInterrupts();  //使能 Core0 的全局中断
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());  //禁用 Core0 的 CPU 看门狗和系统安全看门狗。
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    /**
     * Core0主函数入口
     * 仅负责初始化与主循环任务调度，无底层硬件与具体应用逻辑的依赖（符合AUTOSAR分层规范）
     * 核心职责是 “系统级集成与调度”（确保模块初始化顺序、任务调度正常），而非 “业务细节的实现”（如 LED 初始状态、闪烁逻辑）
     */

    // 1. Port驱动初始化（必须优先执行，符合AUTOSAR Port驱动初始化时序）
    Port_Cfg_Init();
    
    // 2. LED模块初始化（集成工程师仅需调用接口，同时确认关键配置型号，无需关心内部逻辑）
    //Led_Ctrl_Init();
    //Led_Ctrl_Init(&BasicCarConfig);
    //Led_Ctrl_Init(&LuxuryCarConfig);
    Led_Ctrl_Init(&FashionableCarConfig);

    /* Initialize the LED and a time constant before the CPUs synchronization */
    initMulticoreAPSet();

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);  //“向全局广播我的就绪信号” ,逻辑是：找到 event 这个 32 位的变量，根据当前 Core 的 ID，把对应的那个 bit 位置为 1。
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);


    // 3. 主循环：调度LED业务逻辑（集成工程师仅需调用接口，无需关心内部逻辑）
    while(1)
    {
        Led_Ctrl_Handle(); // 调用业务逻辑模块
    }

//前 Port_Cfg_Init 和 Led_Ctrl_Init 的先后顺序依赖于 main.c 里的手动排序。
//后续可引入一个 EcuM (ECU State Manager) 模块，统一管理各层级的初始化序列（Power-up -> MCU Init -> Port Init -> Driver Init -> App Init）。

}
